spring.application.name=CareerContactAPI

# DB
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Properties for authentication (auth0)
okta.oauth2.issuer=https://dev-flb8eq4lk5mmdh3r.us.auth0.com/
okta.oauth2.client-id=NtCvwpfDEqob7rXp0kvDRJMQCClKv3WO
okta.oauth2.client-secret=UMd7jlz01xL7LOLhdoxvhgdAs8lp0jardizmthsPmwmAPWzq-fF5f2p6qL245I7Y
auth0.audience=https://dev-flb8eq4lk5mmdh3r.us.auth0.com/api/v2/
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-flb8eq4lk5mmdh3r.us.auth0.com/

frontend.url=http://localhost:3000/
backend.url=http://localhost:8080/

# Needed separately by Spring Security's built-in OAuth2 login machinery
spring.security.oauth2.client.registration.okta.client-id=NtCvwpfDEqob7rXp0kvDRJMQCClKv3WO
spring.security.oauth2.client.registration.okta.client-secret=UMd7jlz01xL7LOLhdoxvhgdAs8lp0jardizmthsPmwmAPWzq-fF5f2p6qL245I7Y
spring.security.oauth2.client.provider.okta.issuer-uri=https://dev-flb8eq4lk5mmdh3r.us.auth0.com/


# Properties for Amazon AWS S3 bucket (images/pdf)
amazonProperties.endpointUrl=url
amazonProperties.accessKey=some-key
amazonProperties.secretKey=secret-key
amazonProperties.bucketName=careerContact

# Properties for email service
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=careercontact341@gmail.com
#spring.mail.password=$oftwar32026
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true