spring.application.name=CareerContactAPI

# DB
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Properties for authentication (auth0)
okta.oauth2.issuer=https://canadawidecarparts.us.auth0.com/
okta.oauth2.client-id=u2BmgJXKcxNAiQXTxRBOFUb7g6F6K8qE
okta.oauth2.client-secret=mJYR5HD0-wK_IK1XOopzt0Dvmjuylzj3zryJ7i1Zug_1TbMQlA3U44qcYFDHtSxh
okta.oauth2.groups-claim=https://canadawidecarparts/roles
auth0.audience=https://canadawidecarparts.us.auth0.com/api/v2/
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://canadawidecarparts.us.auth0.com/

# Properties for Amazon AWS S3 bucket (images/pdf)
amazonProperties.endpointUrl=url
amazonProperties.accessKey=some-key
amazonProperties.secretKey=secret-key
amazonProperties.bucketName=careerContact

# Properties for email service
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=careercontact341@gmail.com
#spring.mail.password=$oftwar32026
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true