CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id VARCHAR(36) UNIQUE NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    profile_picture_url VARCHAR(255) NULL,
    email VARCHAR(255) UNIQUE NULL
);
